### ISSUE TITLE
WebSocket does not reconnect

### ISSUE THREAD

**Issue by theoriginalgri** [madwire/tutum-nginx-proxy#1]
I tried your image and it works great with virtual hosts and cloudflare ssl! :) The only issue I have is that after running for some hours, the image did not receive events from tutum anymore. I guess this is because the WebSocket does not reconnect or check for connection loss?

Unfortunately Ruby is completely magic in my eyes, so I can't fix this myself ...

**Comment by madwire** [comment]
ok thanks, will take a look

**Comment by madwire** [comment]
@theoriginalgri I have also pushed this change to docker hub :)
