### ISSUE TITLE
More than 25 containers are being ignored.

### ISSUE THREAD

**Issue by samkelleher** [madwire/tutum-nginx-proxy#10]
The call to the `get_services()` api is paginated, and returns 25 at a time with the oldest first.

The ruby script just loads the first page only, thus, once you have more than 25 containers, they are never processed into the config.

The script needs to enumerate them all.  The Tutum docs isn't clear that the call is paginated.

I don't know enough Ruby to be able to do this work myself, but would make good PR if somebody has the necessary skills.

**Comment by madwire** [comment]
@samkelleher Thanks I will take a look.

**Comment by madwire** [comment]
@samkelleher I have created a PR (#11) with a fix to this issue and kicked off a build on docker hub (tagged as fix-services-pagination-issue): https://hub.docker.com/r/madwire/tutum-nginx-proxy/builds/

give that a go, if it solves the problem and doesn't have any adverse effects I will merge it into master

**Comment by madwire** [comment]
@samkelleher Did this work for you?

**Comment by madwire** [comment]
@samkelleher Did this work for you?

**Comment by samkelleher** [comment]
Sorry @madwire I must have missed the follow up notification! 😶Someone else pulled in your PR with thanks, and they tell me that it fixed the issue. Thank you so much 👏

I'll go ahead and close the issue but the PR looks good to merge.
